### ISSUE TITLE
osx travis tests are failing with recent dependency changes.

### ISSUE THREAD

**Issue by ganeshmaharaj** [kata-containers/tests#1862]
This repository has as recent change where all the dependencies & vendor files are unified at the top level. With this change, it seems like osx tests are failing with the below error. 
```
# github.com/kata-containers/tests/vendor/github.com/sirupsen/logrus
../../vendor/github.com/sirupsen/logrus/logger.go:20:8: undefined: LevelHooks
make: *** [kata-check-markdown] Error 2
The command "bash .ci/static-checks.sh github.com/kata-containers/tests" exited with 2.
```
Moving osx tests to allow_failures tab for now.

**Comment by GabyCT** [comment]
Closing this issue as it has been fixed

**Comment by chavafg** [comment]
I still see next errors on osx:
```
0.01s$ travis_install_go_dependencies 1.11.x -v
2.42s$ bash .ci/static-checks.sh github.com/kata-containers/tests
INFO: Running 'static_check_commits' function
Makefile:10: /etc/os-release: No such file or directory
make: *** No rule to make target `/etc/os-release'.  Stop.
```
from: https://travis-ci.org/github/kata-containers/tests/jobs/665760078?utm_medium=notification&utm_source=github_status 

We have allowed failures on osx, that is why we do not notice it is still failing. 

Do we still care about OSX? /cc @kata-containers/architecture-committee 

If we do, I know @GabyCT and @jcvenegas now have macs 😄, so if you have a chance, it would be good to take a look at the current issues.
