### ISSUE TITLE
CLH+CRIO K8S tests failing with kata 2.x

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/tests#2995]
Some k8s tests are failing with kata 2.x and CLH+CRIO
The tests were pods can't be created are
k8s-liveness-probes.bats
k8s-copy-file.bats
/cc @likebreath @jcvenegas

**Comment by GabyCT** [comment]
Here are some log details
<details>
<summary>Runtime config files</summary>
<p>


# Runtime config files


## Runtime default config files

```
/etc/kata-containers/configuration.toml
/usr/share/defaults/kata-containers/configuration.toml
```

## Runtime config file contents

Config file `/etc/kata-containers/configuration.toml` not found
<details>
<summary><tt>cat "/usr/share/defaults/kata-containers/configuration.toml"</tt></summary>
<p>

```toml
# Copyright (c) 2019 Ericsson Eurolab Deutschland GmbH
#
# SPDX-License-Identifier: Apache-2.0
#

# XXX: WARNING: this file is auto-generated.
# XXX:
# XXX: Source file: "cli/config/configuration-clh.toml.in"
# XXX: Project:
# XXX:   Name: Kata Containers
# XXX:   Type: kata

[hypervisor.clh]
path = "/usr/bin/cloud-hypervisor"
kernel = "/usr/share/kata-containers/vmlinux-virtiofs.container"
image = "/usr/share/kata-containers/kata-containers.img"

# List of valid annotation names for the hypervisor
# Each member of the list is a regular expression, which is the base name
# of the annotation, e.g. "path" for io.katacontainers.config.hypervisor.path"
enable_annotations = []

# List of valid annotations values for the hypervisor
# Each member of the list is a path pattern as described by glob(3).
# The default if not set is empty (all annotations rejected.)
# Your distribution recommends: ["/usr/bin/cloud-hypervisor"]
valid_hypervisor_paths = ["/usr/bin/cloud-hypervisor"]

# Optional space-separated list of options to pass to the guest kernel.
# For example, use `kernel_params = "vsyscall=emulate"` if you are having
# trouble running pre-2.15 glibc.
#
# WARNING: - any parameter specified here will take priority over the default
# parameter value of the same name used to start the virtual machine.
# Do not set values here unless you understand the impact of doing so as you
# may stop the virtual machine from booting.
# To see the list of default parameters, enable hypervisor debug, create a
# container and look for 'default-kernel-parameters' log entries.
kernel_params = " agent.log=debug"

# Default number of vCPUs per SB/VM:
# unspecified or 0                --> will be set to 1
# < 0                             --> will be set to the actual number of physical cores
# > 0 <= number of physical cores --> will be set to the specified number
# > number of physical cores      --> will be set to the actual number of physical cores
default_vcpus = 1

# Default maximum number of vCPUs per SB/VM:
# unspecified or == 0             --> will be set to the actual number of physical cores or to the maximum number
#                                     of vCPUs supported by KVM if that number is exceeded
# > 0 <= number of physical cores --> will be set to the specified number
# > number of physical cores      --> will be set to the actual number of physical cores or to the maximum number
#                                     of vCPUs supported by KVM if that number is exceeded
# WARNING: Depending of the architecture, the maximum number of vCPUs supported by KVM is used when
# the actual number of physical cores is greater than it.
# WARNING: Be aware that this value impacts the virtual machine's memory footprint and CPU
# the hotplug functionality. For example, `default_maxvcpus = 240` specifies that until 240 vCPUs
# can be added to a SB/VM, but the memory footprint will be big. Another example, with
# `default_maxvcpus = 8` the memory footprint will be small, but 8 will be the maximum number of
# vCPUs supported by the SB/VM. In general, we recommend that you do not edit this variable,
# unless you know what are you doing.
default_maxvcpus = 0

# Default memory size in MiB for SB/VM.
# If unspecified then it will be set 2048 MiB.
default_memory = 2048

# Default memory slots per SB/VM.
# If unspecified then it will be set 10.
# This is will determine the times that memory will be hotadded to sandbox/VM.
#memory_slots = 10

# Path to vhost-user-fs daemon.
virtio_fs_daemon = "/usr/libexec/kata-qemu/virtiofsd"

# List of valid annotations values for the virtiofs daemon
# The default if not set is empty (all annotations rejected.)
# Your distribution recommends: ["/usr/libexec/kata-qemu/virtiofsd"]
valid_virtio_fs_daemon_paths = ["/usr/libexec/kata-qemu/virtiofsd"]

# Default size of DAX cache in MiB
virtio_fs_cache_size = 0

# Extra args for virtiofsd daemon
#
# Format example:
#   ["-o", "arg1=xxx,arg2", "-o", "hello world", "--arg3=yyy"]
#
# see `virtiofsd -h` for possible options.
virtio_fs_extra_args = ["--thread-pool-size=1"]

# Cache mode:
#
#  - none
#    Metadata, data, and pathname lookup are not cached in guest. They are
#    always fetched from host and any changes are immediately pushed to host.
#
#  - auto
#    Metadata and pathname lookup cache expires after a configured amount of
#    time (default is 1 second). Data is cached while the file is open (close
#    to open consistency).
#
#  - always
#    Metadata, data, and pathname lookup are cached in guest and never expire.
virtio_fs_cache = "auto"

# Block storage driver to be used for the hypervisor in case the container
# rootfs is backed by a block device. This is virtio-scsi, virtio-blk
# or nvdimm.
block_device_driver = "virtio-blk"

# This option changes the default hypervisor and kernel parameters
# to enable debug output where available.
#
# Default false
enable_debug = true

[agent.kata]
# If enabled, make the agent display debug-level messages.
# (default: disabled)
enable_debug = true

# Enable agent tracing.
#
# If enabled, the default trace mode is "dynamic" and the
# default trace type is "isolated". The trace mode and type are set
# explicity with the `trace_type=` and `trace_mode=` options.
#
# Notes:
#
# - Tracing is ONLY enabled when `enable_tracing` is set: explicitly
#   setting `trace_mode=` and/or `trace_type=` without setting `enable_tracing`
#   will NOT activate agent tracing.
#
# - See https://github.com/kata-containers/agent/blob/master/TRACING.md for
#   full details.
#
# (default: disabled)
#enable_tracing = true
#
#trace_mode = "dynamic"
#trace_type = "isolated"

# Enable debug console.

# If enabled, user can connect guest OS running inside hypervisor
# through "kata-runtime exec <sandbox-id>" command

#debug_console_enabled = true

[netmon]
# If enabled, the network monitoring process gets started when the
# sandbox is created. This allows for the detection of some additional
# network being added to the existing network namespace, after the
# sandbox has been created.
# (default: disabled)
#enable_netmon = true

# Specify the path to the netmon binary.
path = "/usr/libexec/kata-containers/kata-netmon"

# If enabled, netmon messages will be sent to the system log
# (default: disabled)
enable_debug = true


[runtime]
# If enabled, the runtime will log additional debug messages to the
# system log
# (default: disabled)
enable_debug = true
#
# Internetworking model
# Determines how the VM should be connected to the
# the container network interface
# Options:
#
#   - bridged (Deprecated)
#     Uses a linux bridge to interconnect the container interface to
#     the VM. Works for most cases except macvlan and ipvlan.
#     ***NOTE: This feature has been deprecated with plans to remove this
#     feature in the future. Please use other network models listed below.
#
#
#   - macvtap
#     Used when the Container network interface can be bridged using
#     macvtap.
#
#   - none
#     Used when customize network. Only creates a tap device. No veth pair.
#
#   - tcfilter
#     Uses tc filter rules to redirect traffic from the network interface
#     provided by plugin to a tap interface connected to the VM.
#
internetworking_model="tcfilter"

# disable guest seccomp
# Determines whether container seccomp profiles are passed to the virtual
# machine and applied by the kata agent. If set to true, seccomp is not applied
# within the guest
# (default: true)
disable_guest_seccomp=true

# If enabled, the runtime will create opentracing.io traces and spans.
# (See https://www.jaegertracing.io/docs/getting-started).
# (default: disabled)
#enable_tracing = true

# If enabled, the runtime will not create a network namespace for shim and hypervisor processes.
# This option may have some potential impacts to your host. It should only be used when you know what you're doing.
# `disable_new_netns` conflicts with `enable_netmon`
# `disable_new_netns` conflicts with `internetworking_model=bridged` and `internetworking_model=macvtap`. It works only
# with `internetworking_model=none`. The tap device will be in the host network namespace and can connect to a bridge
# (like OVS) directly.
# If you are using docker, `disable_new_netns` only works with `docker run --net=none`
# (default: false)
#disable_new_netns = true

# if enabled, the runtime will add all the kata processes inside one dedicated cgroup.
# The container cgroups in the host are not created, just one single cgroup per sandbox.
# The runtime caller is free to restrict or collect cgroup stats of the overall Kata sandbox.
# The sandbox cgroup path is the parent cgroup of a container with the PodSandbox annotation.
# The sandbox cgroup is constrained if there is no container type annotation.
# See: https://godoc.org/github.com/kata-containers/runtime/virtcontainers#ContainerType
sandbox_cgroup_only=false

# Enabled experimental feature list, format: ["a", "b"].
# Experimental features are features not stable enough for production,
# they may break compatibility, and are prepared for a big version bump.
# Supported experimental features:
# (default: [])
experimental=[]

# If enabled, user can run pprof tools with shim v2 process through kata-monitor.
# (default: false)
# EnablePprof = true
```

</p>
</details>

---


</p>
</details>
<details>
<summary>Containerd shim v2</summary>
<p>

Containerd shim v2 is `/usr/local/bin/containerd-shim-kata-v2`.
<details>
<summary><tt>containerd-shim-kata-v2 --version</tt></summary>
<p>

```
Kata Containers containerd shim: id: "io.containerd.kata.v2", version: 2.0.0-rc0, commit: d80e479ca201d3fdf75305b07e22ccc15ef6dda3
```

</p>
</details>

---


</p>
</details>
<details>
<summary>KSM throttler</summary>
<p>


# KSM throttler


## version


## systemd service


</p>
</details>
<details>
<summary>Image details</summary>
<p>


# Image details

```yaml
---
osbuilder:
  url: "https://github.com/kata-containers/kata-containers/tools/osbuilder"
  version: "2.0.0-rc0-d80e479ca201d3fdf75305b07e22ccc15ef6dda3"
rootfs-creation-time: "2020-10-20T19:24:45.373267824+0000Z"
description: "osbuilder rootfs"
file-format-version: "0.0.2"
architecture: "x86_64"
base-distro:
  name: "bionic"
  version: "18.04"
  packages:
    default:
      - "chrony"
      - "init"
      - "iptables"
      - "kmod"
      - "systemd"
    extra:

agent:
  url: "https://github.com/kata-containers/kata-containers"
  name: "kata-agent"
  version: "2.0.0-rc0"
  agent-is-init-daemon: "no"
```

---


</p>
</details>
<details>
<summary>Initrd details</summary>
<p>


# Initrd details

No initrd

---


</p>
</details>
<details>
<summary>Logfiles</summary>
<p>


# Logfiles


## Runtime logs

<details>
<summary>Runtime logs</summary>
<p>

No recent runtime problems found in system journal.

</p>
</details>

## Throttler logs

<details>
<summary>Throttler logs</summary>
<p>

No recent throttler problems found in system journal.

</p>
</details>

## Kata Containerd Shim v2 logs

<details>
<summary>Kata Containerd Shim v2</summary>
<p>

Recent  problems found in system journal:
```
time="2020-10-20T20:36:50.938227666Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938286867Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938345469Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.93840707Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938463872Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938518573Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938577575Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938628776Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938696178Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938749379Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938823081Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938899083Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.938979386Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939036087Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939088288Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.93914839Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939201291Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939268193Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939324095Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939394097Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939479099Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.9395374Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939597002Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939644503Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939725905Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939797707Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939856209Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.939929111Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940000913Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940076515Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940149216Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940206618Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940262419Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940324721Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940381223Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940441924Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940501926Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940558727Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940608529Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.94066553Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940730732Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940793734Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940851135Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940903636Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.940962238Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.941009739Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.941074841Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.941168343Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.941226445Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
time="2020-10-20T20:36:50.950908301Z" level=warning msg="failed to get OOM event from sandbox" error="ttrpc: closed" pid=25976 sandbox=e486fd15e87b4a02bc5fcd79146469936c964582461664685a88dfbbbfbfff5f source=containerd-kata-shim-v2
```

</p>
</details>

---


</p>
</details>
<details>
<summary>Container manager details</summary>
<p>


# Container manager details

<details>
<summary>Docker</summary>
<p>


## Docker

<details>
<summary><tt>docker version</tt></summary>
<p>

```
Client:
 Version:           18.06.3-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        d7080c1
 Built:             Wed Feb 20 02:28:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.3-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       d7080c1
  Built:            Wed Feb 20 02:26:34 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

</p>
</details>
<details>
<summary><tt>docker info</tt></summary>
<p>

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 33
Server Version: 18.06.3-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: a592beb5bc4c4092b1b1bac971afed27687340c5
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.4.0-1031-azure
Operating System: Ubuntu 18.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.64GiB
Name: testcrioclh
ID: APTO:XVPD:5BEW:QLYH:TDT5:LGH4:RPVT:IGN3:ZC2L:VBOH:IGNR:6PNF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

</p>
</details>
<details>
<summary><tt>systemctl show docker</tt></summary>
<p>

```
Type=notify
Restart=on-failure
NotifyAccess=main
RestartUSec=100ms
TimeoutStartUSec=infinity
TimeoutStopUSec=1min 30s
RuntimeMaxUSec=infinity
WatchdogUSec=0
WatchdogTimestamp=Tue 2020-10-20 19:13:54 UTC
WatchdogTimestampMonotonic=1974119628
PermissionsStartOnly=no
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=yes
MainPID=15522
ControlPID=0
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusErrno=0
Result=success
UID=[not set]
GID=[not set]
NRestarts=0
ExecMainStartTimestamp=Tue 2020-10-20 19:13:54 UTC
ExecMainStartTimestampMonotonic=1973791825
ExecMainExitTimestampMonotonic=0
ExecMainPID=15522
ExecMainCode=0
ExecMainStatus=0
ExecStart={ path=/usr/bin/dockerd ; argv[]=/usr/bin/dockerd -H fd:// ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
ExecReload={ path=/bin/kill ; argv[]=/bin/kill -s HUP $MAINPID ; ignore_errors=no ; start_time=[n/a] ; stop_time=[n/a] ; pid=0 ; code=(null) ; status=0/0 }
Slice=system.slice
ControlGroup=/system.slice/docker.service
MemoryCurrent=[not set]
CPUUsageNSec=[not set]
TasksCurrent=36
IPIngressBytes=18446744073709551615
IPIngressPackets=18446744073709551615
IPEgressBytes=18446744073709551615
IPEgressPackets=18446744073709551615
Delegate=yes
DelegateControllers=cpu cpuacct io blkio memory devices pids
CPUAccounting=no
CPUWeight=[not set]
StartupCPUWeight=[not set]
CPUShares=[not set]
StartupCPUShares=[not set]
CPUQuotaPerSecUSec=infinity
IOAccounting=no
IOWeight=[not set]
StartupIOWeight=[not set]
BlockIOAccounting=no
BlockIOWeight=[not set]
StartupBlockIOWeight=[not set]
MemoryAccounting=no
MemoryLow=0
MemoryHigh=infinity
MemoryMax=infinity
MemorySwapMax=infinity
MemoryLimit=infinity
DevicePolicy=auto
TasksAccounting=yes
TasksMax=infinity
IPAccounting=no
UMask=0022
LimitCPU=infinity
LimitCPUSoft=infinity
LimitFSIZE=infinity
LimitFSIZESoft=infinity
LimitDATA=infinity
LimitDATASoft=infinity
LimitSTACK=infinity
LimitSTACKSoft=8388608
LimitCORE=infinity
LimitCORESoft=infinity
LimitRSS=infinity
LimitRSSSoft=infinity
LimitNOFILE=1048576
LimitNOFILESoft=1048576
LimitAS=infinity
LimitASSoft=infinity
LimitNPROC=infinity
LimitNPROCSoft=infinity
LimitMEMLOCK=16777216
LimitMEMLOCKSoft=16777216
LimitLOCKS=infinity
LimitLOCKSSoft=infinity
LimitSIGPENDING=63912
LimitSIGPENDINGSoft=63912
LimitMSGQUEUE=819200
LimitMSGQUEUESoft=819200
LimitNICE=0
LimitNICESoft=0
LimitRTPRIO=0
LimitRTPRIOSoft=0
LimitRTTIME=infinity
LimitRTTIMESoft=infinity
OOMScoreAdjust=0
Nice=0
IOSchedulingClass=0
IOSchedulingPriority=0
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardInputData=
StandardOutput=journal
StandardError=inherit
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogLevelPrefix=yes
SyslogLevel=6
SyslogFacility=3
LogLevelMax=-1
SecureBits=0
CapabilityBoundingSet=cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend
AmbientCapabilities=
DynamicUser=no
RemoveIPC=no
MountFlags=
PrivateTmp=no
PrivateDevices=no
ProtectKernelTunables=no
ProtectKernelModules=no
ProtectControlGroups=no
PrivateNetwork=no
PrivateUsers=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
UtmpMode=init
IgnoreSIGPIPE=yes
NoNewPrivileges=no
SystemCallErrorNumber=0
LockPersonality=no
RuntimeDirectoryPreserve=no
RuntimeDirectoryMode=0755
StateDirectoryMode=0755
CacheDirectoryMode=0755
LogsDirectoryMode=0755
ConfigurationDirectoryMode=0755
MemoryDenyWriteExecute=no
RestrictRealtime=no
RestrictSUIDSGID=no
RestrictNamespaces=no
MountAPIVFS=no
KeyringMode=private
KillMode=process
KillSignal=15
SendSIGKILL=yes
SendSIGHUP=no
Id=docker.service
Names=docker.service
Requires=docker.socket sysinit.target system.slice
Wants=network-online.target
WantedBy=multi-user.target
ConsistsOf=docker.socket
Conflicts=shutdown.target
Before=multi-user.target shutdown.target
After=network-online.target system.slice basic.target sysinit.target systemd-journald.socket firewalld.service docker.socket
TriggeredBy=docker.socket
Documentation=https://docs.docker.com
Description=Docker Application Container Engine
LoadState=loaded
ActiveState=active
SubState=running
FragmentPath=/lib/systemd/system/docker.service
UnitFileState=enabled
UnitFilePreset=enabled
StateChangeTimestamp=Tue 2020-10-20 19:13:54 UTC
StateChangeTimestampMonotonic=1974119630
InactiveExitTimestamp=Tue 2020-10-20 19:13:54 UTC
InactiveExitTimestampMonotonic=1973791906
ActiveEnterTimestamp=Tue 2020-10-20 19:13:54 UTC
ActiveEnterTimestampMonotonic=1974119630
ActiveExitTimestamp=Tue 2020-10-20 19:13:53 UTC
ActiveExitTimestampMonotonic=1972779667
InactiveEnterTimestamp=Tue 2020-10-20 19:13:54 UTC
InactiveEnterTimestampMonotonic=1973785664
CanStart=yes
CanStop=yes
CanReload=yes
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Tue 2020-10-20 19:13:54 UTC
ConditionTimestampMonotonic=1973790672
AssertTimestamp=Tue 2020-10-20 19:13:54 UTC
AssertTimestampMonotonic=1973790673
Transient=no
Perpetual=no
StartLimitIntervalUSec=1min
StartLimitBurst=3
StartLimitAction=none
FailureAction=none
SuccessAction=none
InvocationID=6c415385ab884891b871a29898b78a5d
CollectMode=inactive
```

</p>
</details>

</p>
</details>
<details>
<summary>Kubernetes</summary>
<p>


## Kubernetes

<details>
<summary><tt>kubectl version</tt></summary>
<p>

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9", GitCommit:"94f372e501c973a7fa9eb40ec9ebd2fe7ca69848", GitTreeState:"clean", BuildDate:"2020-09-16T13:56:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 10.1.2.4:6443 was refused - did you specify the right host or port?
```

</p>
</details>
<details>
<summary><tt>kubectl config view</tt></summary>
<p>

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://10.1.2.4:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
```

</p>
</details>
<details>
<summary><tt>systemctl show kubelet</tt></summary>
<p>

```
Type=simple
Restart=always
NotifyAccess=none
RestartUSec=10s
TimeoutStartUSec=1min 30s
TimeoutStopUSec=1min 30s
RuntimeMaxUSec=infinity
WatchdogUSec=0
WatchdogTimestampMonotonic=0
PermissionsStartOnly=no
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=yes
MainPID=0
ControlPID=0
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusErrno=0
Result=success
UID=[not set]
GID=[not set]
NRestarts=0
ExecMainStartTimestamp=Tue 2020-10-20 20:31:51 UTC
ExecMainStartTimestampMonotonic=6650782190
ExecMainExitTimestamp=Tue 2020-10-20 20:37:41 UTC
ExecMainExitTimestampMonotonic=7001231611
ExecMainPID=8931
ExecMainCode=1
ExecMainStatus=0
ExecStart={ path=/usr/bin/kubelet ; argv[]=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS ; ignore_errors=no ; start_time=[Tue 2020-10-20 20:31:51 UTC] ; stop_time=[Tue 2020-10-20 20:37:41 UTC] ; pid=8931 ; code=exited ; status=0 }
Slice=system.slice
MemoryCurrent=[not set]
CPUUsageNSec=[not set]
TasksCurrent=[not set]
IPIngressBytes=18446744073709551615
IPIngressPackets=18446744073709551615
IPEgressBytes=18446744073709551615
IPEgressPackets=18446744073709551615
Delegate=no
CPUAccounting=no
CPUWeight=[not set]
StartupCPUWeight=[not set]
CPUShares=[not set]
StartupCPUShares=[not set]
CPUQuotaPerSecUSec=infinity
IOAccounting=no
IOWeight=[not set]
StartupIOWeight=[not set]
BlockIOAccounting=no
BlockIOWeight=[not set]
StartupBlockIOWeight=[not set]
MemoryAccounting=no
MemoryLow=0
MemoryHigh=infinity
MemoryMax=infinity
MemorySwapMax=infinity
MemoryLimit=infinity
DevicePolicy=auto
TasksAccounting=yes
TasksMax=4915
IPAccounting=no
Environment=[unprintable] [unprintable] KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml
EnvironmentFile=/var/lib/kubelet/kubeadm-flags.env (ignore_errors=yes)
EnvironmentFile=/etc/default/kubelet (ignore_errors=yes)
UMask=0022
LimitCPU=infinity
LimitCPUSoft=infinity
LimitFSIZE=infinity
LimitFSIZESoft=infinity
LimitDATA=infinity
LimitDATASoft=infinity
LimitSTACK=infinity
LimitSTACKSoft=8388608
LimitCORE=infinity
LimitCORESoft=0
LimitRSS=infinity
LimitRSSSoft=infinity
LimitNOFILE=4096
LimitNOFILESoft=1024
LimitAS=infinity
LimitASSoft=infinity
LimitNPROC=63912
LimitNPROCSoft=63912
LimitMEMLOCK=16777216
LimitMEMLOCKSoft=16777216
LimitLOCKS=infinity
LimitLOCKSSoft=infinity
LimitSIGPENDING=63912
LimitSIGPENDINGSoft=63912
LimitMSGQUEUE=819200
LimitMSGQUEUESoft=819200
LimitNICE=0
LimitNICESoft=0
LimitRTPRIO=0
LimitRTPRIOSoft=0
LimitRTTIME=infinity
LimitRTTIMESoft=infinity
OOMScoreAdjust=0
Nice=0
IOSchedulingClass=0
IOSchedulingPriority=0
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardInputData=
StandardOutput=journal
StandardError=inherit
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogLevelPrefix=yes
SyslogLevel=6
SyslogFacility=3
LogLevelMax=-1
SecureBits=0
CapabilityBoundingSet=cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend
AmbientCapabilities=
DynamicUser=no
RemoveIPC=no
MountFlags=
PrivateTmp=no
PrivateDevices=no
ProtectKernelTunables=no
ProtectKernelModules=no
ProtectControlGroups=no
PrivateNetwork=no
PrivateUsers=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
UtmpMode=init
IgnoreSIGPIPE=yes
NoNewPrivileges=no
SystemCallErrorNumber=0
LockPersonality=no
RuntimeDirectoryPreserve=no
RuntimeDirectoryMode=0755
StateDirectoryMode=0755
CacheDirectoryMode=0755
LogsDirectoryMode=0755
ConfigurationDirectoryMode=0755
MemoryDenyWriteExecute=no
RestrictRealtime=no
RestrictSUIDSGID=no
RestrictNamespaces=no
MountAPIVFS=no
KeyringMode=private
KillMode=control-group
KillSignal=15
SendSIGKILL=yes
SendSIGHUP=no
Id=kubelet.service
Names=kubelet.service
Requires=system.slice sysinit.target
Wants=network-online.target
WantedBy=multi-user.target
Conflicts=shutdown.target
Before=multi-user.target shutdown.target
After=sysinit.target system.slice systemd-journald.socket basic.target network-online.target
Documentation=https://kubernetes.io/docs/home/
Description=kubelet: The Kubernetes Node Agent
LoadState=loaded
ActiveState=inactive
SubState=dead
FragmentPath=/lib/systemd/system/kubelet.service
DropInPaths=/etc/systemd/system/kubelet.service.d/0-crio.conf /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
UnitFileState=enabled
UnitFilePreset=enabled
StateChangeTimestamp=Tue 2020-10-20 20:37:41 UTC
StateChangeTimestampMonotonic=7001231695
InactiveExitTimestamp=Tue 2020-10-20 20:31:51 UTC
InactiveExitTimestampMonotonic=6650782247
ActiveEnterTimestamp=Tue 2020-10-20 20:31:51 UTC
ActiveEnterTimestampMonotonic=6650782247
ActiveExitTimestamp=Tue 2020-10-20 20:37:41 UTC
ActiveExitTimestampMonotonic=7001181498
InactiveEnterTimestamp=Tue 2020-10-20 20:37:41 UTC
InactiveEnterTimestampMonotonic=7001231695
CanStart=yes
CanStop=yes
CanReload=no
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Tue 2020-10-20 20:31:51 UTC
ConditionTimestampMonotonic=6650780625
AssertTimestamp=Tue 2020-10-20 20:31:51 UTC
AssertTimestampMonotonic=6650780626
Transient=no
Perpetual=no
StartLimitIntervalUSec=0
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
SuccessAction=none
InvocationID=c86f28ceee3346879d881090ee8bedd2
CollectMode=inactive
```

</p>
</details>

</p>
</details>
<details>
<summary>crio</summary>
<p>


## crio

<details>
<summary><tt>crio --version</tt></summary>
<p>

```
crio version 1.18.3
Version:       1.18.3
GitCommit:     61de18161fb4ccda720768c001713592b5a04e46
GitTreeState:  clean
BuildDate:     2020-10-20T19:47:53Z
GoVersion:     go1.14.4
Compiler:      gc
Platform:      linux/amd64
Linkmode:      dynamic
```

</p>
</details>
<details>
<summary><tt>systemctl show crio</tt></summary>
<p>

```
Type=simple
Restart=on-failure
NotifyAccess=none
RestartUSec=5s
TimeoutStartUSec=1min 30s
TimeoutStopUSec=1min 30s
RuntimeMaxUSec=infinity
WatchdogUSec=0
WatchdogTimestampMonotonic=0
PermissionsStartOnly=no
RootDirectoryStartOnly=no
RemainAfterExit=no
GuessMainPID=yes
MainPID=0
ControlPID=0
FileDescriptorStoreMax=0
NFileDescriptorStore=0
StatusErrno=0
Result=timeout
UID=[not set]
GID=[not set]
NRestarts=0
ExecMainStartTimestamp=Tue 2020-10-20 20:31:25 UTC
ExecMainStartTimestampMonotonic=6624946404
ExecMainExitTimestamp=Tue 2020-10-20 20:38:05 UTC
ExecMainExitTimestampMonotonic=7025542582
ExecMainPID=7409
ExecMainCode=1
ExecMainStatus=0
ExecStart={ path=/usr/local/bin/crio ; argv[]=/usr/local/bin/crio --log-level debug ; ignore_errors=no ; start_time=[Tue 2020-10-20 20:31:25 UTC] ; stop_time=[Tue 2020-10-20 20:38:05 UTC] ; pid=7409 ; code=exited ; status=0 }
Slice=system.slice
MemoryCurrent=[not set]
CPUUsageNSec=[not set]
TasksCurrent=[not set]
IPIngressBytes=18446744073709551615
IPIngressPackets=18446744073709551615
IPEgressBytes=18446744073709551615
IPEgressPackets=18446744073709551615
Delegate=no
CPUAccounting=no
CPUWeight=[not set]
StartupCPUWeight=[not set]
CPUShares=[not set]
StartupCPUShares=[not set]
CPUQuotaPerSecUSec=infinity
IOAccounting=no
IOWeight=[not set]
StartupIOWeight=[not set]
BlockIOAccounting=no
BlockIOWeight=[not set]
StartupBlockIOWeight=[not set]
MemoryAccounting=no
MemoryLow=0
MemoryHigh=infinity
MemoryMax=infinity
MemorySwapMax=infinity
MemoryLimit=infinity
DevicePolicy=auto
TasksAccounting=yes
TasksMax=4915
IPAccounting=no
UMask=0022
LimitCPU=infinity
LimitCPUSoft=infinity
LimitFSIZE=infinity
LimitFSIZESoft=infinity
LimitDATA=infinity
LimitDATASoft=infinity
LimitSTACK=infinity
LimitSTACKSoft=8388608
LimitCORE=infinity
LimitCORESoft=0
LimitRSS=infinity
LimitRSSSoft=infinity
LimitNOFILE=4096
LimitNOFILESoft=1024
LimitAS=infinity
LimitASSoft=infinity
LimitNPROC=63912
LimitNPROCSoft=63912
LimitMEMLOCK=16777216
LimitMEMLOCKSoft=16777216
LimitLOCKS=infinity
LimitLOCKSSoft=infinity
LimitSIGPENDING=63912
LimitSIGPENDINGSoft=63912
LimitMSGQUEUE=819200
LimitMSGQUEUESoft=819200
LimitNICE=0
LimitNICESoft=0
LimitRTPRIO=0
LimitRTPRIOSoft=0
LimitRTTIME=infinity
LimitRTTIMESoft=infinity
OOMScoreAdjust=0
Nice=0
IOSchedulingClass=0
IOSchedulingPriority=0
CPUSchedulingPolicy=0
CPUSchedulingPriority=0
TimerSlackNSec=50000
CPUSchedulingResetOnFork=no
NonBlocking=no
StandardInput=null
StandardInputData=
StandardOutput=journal
StandardError=inherit
TTYReset=no
TTYVHangup=no
TTYVTDisallocate=no
SyslogPriority=30
SyslogLevelPrefix=yes
SyslogLevel=6
SyslogFacility=3
LogLevelMax=-1
SecureBits=0
CapabilityBoundingSet=cap_chown cap_dac_override cap_dac_read_search cap_fowner cap_fsetid cap_kill cap_setgid cap_setuid cap_setpcap cap_linux_immutable cap_net_bind_service cap_net_broadcast cap_net_admin cap_net_raw cap_ipc_lock cap_ipc_owner cap_sys_module cap_sys_rawio cap_sys_chroot cap_sys_ptrace cap_sys_pacct cap_sys_admin cap_sys_boot cap_sys_nice cap_sys_resource cap_sys_time cap_sys_tty_config cap_mknod cap_lease cap_audit_write cap_audit_control cap_setfcap cap_mac_override cap_mac_admin cap_syslog cap_wake_alarm cap_block_suspend
AmbientCapabilities=
DynamicUser=no
RemoveIPC=no
MountFlags=
PrivateTmp=no
PrivateDevices=no
ProtectKernelTunables=no
ProtectKernelModules=no
ProtectControlGroups=no
PrivateNetwork=no
PrivateUsers=no
ProtectHome=no
ProtectSystem=no
SameProcessGroup=no
UtmpMode=init
IgnoreSIGPIPE=yes
NoNewPrivileges=no
SystemCallErrorNumber=0
LockPersonality=no
RuntimeDirectoryPreserve=no
RuntimeDirectoryMode=0755
StateDirectoryMode=0755
CacheDirectoryMode=0755
LogsDirectoryMode=0755
ConfigurationDirectoryMode=0755
MemoryDenyWriteExecute=no
RestrictRealtime=no
RestrictSUIDSGID=no
RestrictNamespaces=no
MountAPIVFS=no
KeyringMode=private
KillMode=control-group
KillSignal=15
SendSIGKILL=yes
SendSIGHUP=no
Id=crio.service
Names=crio.service
Requires=system.slice sysinit.target
Conflicts=shutdown.target
Before=shutdown.target
After=sysinit.target systemd-journald.socket system.slice basic.target
Documentation=https://github.com/cri-o/cri-o
Description=CRI-O daemon
LoadState=loaded
ActiveState=failed
SubState=failed
FragmentPath=/etc/systemd/system/crio.service
UnitFileState=disabled
UnitFilePreset=enabled
StateChangeTimestamp=Tue 2020-10-20 20:39:35 UTC
StateChangeTimestampMonotonic=7115632199
InactiveExitTimestamp=Tue 2020-10-20 20:31:25 UTC
InactiveExitTimestampMonotonic=6624946483
ActiveEnterTimestamp=Tue 2020-10-20 20:31:25 UTC
ActiveEnterTimestampMonotonic=6624946483
ActiveExitTimestamp=Tue 2020-10-20 20:38:05 UTC
ActiveExitTimestampMonotonic=7025519200
InactiveEnterTimestamp=Tue 2020-10-20 20:39:35 UTC
InactiveEnterTimestampMonotonic=7115632199
CanStart=yes
CanStop=yes
CanReload=no
CanIsolate=no
StopWhenUnneeded=no
RefuseManualStart=no
RefuseManualStop=no
AllowIsolate=no
DefaultDependencies=yes
OnFailureJobMode=replace
IgnoreOnIsolate=no
NeedDaemonReload=no
JobTimeoutUSec=infinity
JobRunningTimeoutUSec=infinity
JobTimeoutAction=none
ConditionResult=yes
AssertResult=yes
ConditionTimestamp=Tue 2020-10-20 20:31:25 UTC
ConditionTimestampMonotonic=6624945094
AssertTimestamp=Tue 2020-10-20 20:31:25 UTC
AssertTimestampMonotonic=6624945095
Transient=no
Perpetual=no
StartLimitIntervalUSec=10s
StartLimitBurst=5
StartLimitAction=none
FailureAction=none
SuccessAction=none
InvocationID=8314d1bb186542448f91e35fbe85c96d
CollectMode=inactive
```

</p>
</details>
<details>
<summary><tt>crio config</tt></summary>
<p>

```
level=info msg="Using default capabilities: CAP_CHOWN, CAP_DAC_OVERRIDE, CAP_FSETID, CAP_FOWNER, CAP_SETGID, CAP_SETUID, CAP_SETPCAP, CAP_NET_BIND_SERVICE, CAP_KILL"
# The CRI-O configuration file specifies all of the available configuration
# options and command-line flags for the crio(8) OCI Kubernetes Container Runtime
# daemon, but in a TOML format that can be more easily modified and versioned.
#
# Please refer to crio.conf(5) for details of all configuration options.

# CRI-O supports partial configuration reload during runtime, which can be
# done by sending SIGHUP to the running process. Currently supported options
# are explicitly mentioned with: 'This option supports live configuration
# reload'.

# CRI-O reads its storage defaults from the containers-storage.conf(5) file
# located at /etc/containers/storage.conf. Modify this storage configuration if
# you want to change the system's defaults. If you want to modify storage just
# for CRI-O, you can change the storage configuration options here.
[crio]

# Path to the "root directory". CRI-O stores all of its data, including
# containers images, in this directory.
#root = "/var/lib/containers/storage"

# Path to the "run directory". CRI-O stores all of its state in this directory.
#runroot = "/var/run/containers/storage"

# Storage driver used to manage the storage of images and containers. Please
# refer to containers-storage.conf(5) to see all available storage drivers.
#storage_driver = ""

# List to pass options to the storage driver. Please refer to
# containers-storage.conf(5) to see all available storage options.
#storage_option = [
#]

# The default log directory where all logs will go unless directly specified by
# the kubelet. The log directory specified must be an absolute directory.
log_dir = "/var/log/crio/pods"

# Location for CRI-O to lay down the temporary version file.
# It is used to check if crio wipe should wipe containers, which should
# always happen on a node reboot
version_file = "/var/run/crio/version"

# Location for CRI-O to lay down the persistent version file.
# It is used to check if crio wipe should wipe images, which should
# only happen when CRI-O has been upgraded
version_file_persist = "/var/lib/crio/version"

# The crio.api table contains settings for the kubelet/gRPC interface.
[crio.api]

# Path to AF_LOCAL socket on which CRI-O will listen.
listen = "/var/run/crio/crio.sock"

# IP address on which the stream server will listen.
stream_address = "127.0.0.1"

# The port on which the stream server will listen. If the port is set to "0", then
# CRI-O will allocate a random free port number.
stream_port = "0"

# Enable encrypted TLS transport of the stream server.
stream_enable_tls = false

# Path to the x509 certificate file used to serve the encrypted stream. This
# file can change, and CRI-O will automatically pick up the changes within 5
# minutes.
stream_tls_cert = ""

# Path to the key file used to serve the encrypted stream. This file can
# change and CRI-O will automatically pick up the changes within 5 minutes.
stream_tls_key = ""

# Path to the x509 CA(s) file used to verify and authenticate client
# communication with the encrypted stream. This file can change and CRI-O will
# automatically pick up the changes within 5 minutes.
stream_tls_ca = ""

# Maximum grpc send message size in bytes. If not set or <=0, then CRI-O will default to 16 * 1024 * 1024.
grpc_max_send_msg_size = 16777216

# Maximum grpc receive message size. If not set or <= 0, then CRI-O will default to 16 * 1024 * 1024.
grpc_max_recv_msg_size = 16777216

# The crio.runtime table contains settings pertaining to the OCI runtime used
# and options for how to set up and manage the OCI runtime.
[crio.runtime]

# A list of ulimits to be set in containers by default, specified as
# "<ulimit name>=<soft limit>:<hard limit>", for example:
# "nofile=1024:2048"
# If nothing is set here, settings will be inherited from the CRI-O daemon
#default_ulimits = [
#]

# default_runtime is the _name_ of the OCI runtime to be used as the default.
# The name is matched against the runtimes map below.
default_runtime = "runc"

# If true, the runtime will not use pivot_root, but instead use MS_MOVE.
no_pivot = false

# decryption_keys_path is the path where the keys required for
# image decryption are stored. This option supports live configuration reload.
decryption_keys_path = "/etc/crio/keys/"

# Path to the conmon binary, used for monitoring the OCI runtime.
# Will be searched for using $PATH if empty.
conmon = ""

# Cgroup setting for conmon
conmon_cgroup = "system.slice"

# Environment variable list for the conmon process, used for passing necessary
# environment variables to conmon or the runtime.
conmon_env = [
	"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
]

# Additional environment variables to set for all the
# containers. These are overridden if set in the
# container image spec or in the container runtime configuration.
default_env = [
]

# If true, SELinux will be used for pod separation on the host.
selinux = false

# Path to the seccomp.json profile which is used as the default seccomp profile
# for the runtime. If not specified, then the internal default seccomp profile
# will be used. This option supports live configuration reload.
seccomp_profile = ""

# Used to change the name of the default AppArmor profile of CRI-O. The default
# profile name is "crio-default". This profile only takes effect if the user
# does not specify a profile via the Kubernetes Pod's metadata annotation. If
# the profile is set to "unconfined", then this equals to disabling AppArmor.
# This option supports live configuration reload.
apparmor_profile = "crio-default"

# Cgroup management implementation used for the runtime.
cgroup_manager = "cgroupfs"

# List of default capabilities for containers. If it is empty or commented out,
# only the capabilities defined in the containers json file by the user/kube
# will be added.
default_capabilities = [
	"CHOWN",
	"DAC_OVERRIDE",
	"FSETID",
	"FOWNER",
	"SETGID",
	"SETUID",
	"SETPCAP",
	"NET_BIND_SERVICE",
	"KILL",
]

# List of default sysctls. If it is empty or commented out, only the sysctls
# defined in the container json file by the user/kube will be added.
default_sysctls = [
]

# List of additional devices. specified as
# "<device-on-host>:<device-on-container>:<permissions>", for example: "--device=/dev/sdc:/dev/xvdc:rwm".
#If it is empty or commented out, only the devices
# defined in the container json file by the user/kube will be added.
additional_devices = [
]

# Path to OCI hooks directories for automatically executed hooks. If one of the
# directories does not exist, then CRI-O will automatically skip them.
hooks_dir = [
	"/usr/share/containers/oci/hooks.d",
]

# List of default mounts for each container. **Deprecated:** this option will
# be removed in future versions in favor of default_mounts_file.
default_mounts = [
]

# Path to the file specifying the defaults mounts for each container. The
# format of the config is /SRC:/DST, one mount per line. Notice that CRI-O reads
# its default mounts from the following two files:
#
#   1) /etc/containers/mounts.conf (i.e., default_mounts_file): This is the
#      override file, where users can either add in their own default mounts, or
#      override the default mounts shipped with the package.
#
#   2) /usr/share/containers/mounts.conf: This is the default file read for
#      mounts. If you want CRI-O to read from a different, specific mounts file,
#      you can change the default_mounts_file. Note, if this is done, CRI-O will
#      only add mounts it finds in this file.
#
#default_mounts_file = ""

# Maximum number of processes allowed in a container.
pids_limit = 1024

# Maximum sized allowed for the container log file. Negative numbers indicate
# that no size limit is imposed. If it is positive, it must be >= 8192 to
# match/exceed conmon's read buffer. The file is truncated and re-opened so the
# limit is never exceeded.
log_size_max = -1

# Whether container output should be logged to journald in addition to the kuberentes log file
log_to_journald = false

# Path to directory in which container exit files are written to by conmon.
container_exits_dir = "/var/run/crio/exits"

# Path to directory for container attach sockets.
container_attach_socket_dir = "/var/run/crio"

# The prefix to use for the source of the bind mounts.
bind_mount_prefix = ""

# If set to true, all containers will run in read-only mode.
read_only = false

# Changes the verbosity of the logs based on the level it is set to. Options
# are fatal, panic, error, warn, info, debug and trace. This option supports
# live configuration reload.
log_level = "info"

# Filter the log messages by the provided regular expression.
# This option supports live configuration reload.
log_filter = ""

# The UID mappings for the user namespace of each container. A range is
# specified in the form containerUID:HostUID:Size. Multiple ranges must be
# separated by comma.
uid_mappings = ""

# The GID mappings for the user namespace of each container. A range is
# specified in the form containerGID:HostGID:Size. Multiple ranges must be
# separated by comma.
gid_mappings = ""

# The minimal amount of time in seconds to wait before issuing a timeout
# regarding the proper termination of the container. The lowest possible
# value is 30s, whereas lower values are not considered by CRI-O.
ctr_stop_timeout = 30

# **DEPRECATED** this option is being replaced by manage_ns_lifecycle, which is described below.
# manage_network_ns_lifecycle = true

# manage_ns_lifecycle determines whether we pin and remove namespaces
# and manage their lifecycle
manage_ns_lifecycle = true

# The directory where the state of the managed namespaces gets tracked.
# Only used when manage_ns_lifecycle is true.
namespaces_dir = "/var/run"

# pinns_path is the path to find the pinns binary, which is needed to manage namespace lifecycle
pinns_path = ""

# The "crio.runtime.runtimes" table defines a list of OCI compatible runtimes.
# The runtime to use is picked based on the runtime_handler provided by the CRI.
# If no runtime_handler is provided, the runtime will be picked based on the level
# of trust of the workload. Each entry in the table should follow the format:
#
#[crio.runtime.runtimes.runtime-handler]
#  runtime_path = "/path/to/the/executable"
#  runtime_type = "oci"
#  runtime_root = "/path/to/the/root"
#
# Where:
# - runtime-handler: name used to identify the runtime
# - runtime_path (optional, string): absolute path to the runtime executable in
#   the host filesystem. If omitted, the runtime-handler identifier should match
#   the runtime executable name, and the runtime executable should be placed
#   in $PATH.
# - runtime_type (optional, string): type of runtime, one of: "oci", "vm". If
#   omitted, an "oci" runtime is assumed.
# - runtime_root (optional, string): root directory for storage of containers
#   state.


[crio.runtime.runtimes.kata]
runtime_path = "/usr/local/bin/containerd-shim-kata-v2"
runtime_type = "vm"
runtime_root = "/run/vc"

[crio.runtime.runtimes.runc]
runtime_path = "/usr/local/bin/crio-runc"
runtime_type = "oci"
runtime_root = "/run/runc"


# Kata Containers is an OCI runtime, where containers are run inside lightweight
# VMs. Kata provides additional isolation towards the host, minimizing the host attack
# surface and mitigating the consequences of containers breakout.

# Kata Containers with the default configured VMM
#[crio.runtime.runtimes.kata-runtime]

# Kata Containers with the QEMU VMM
#[crio.runtime.runtimes.kata-qemu]

# Kata Containers with the Firecracker VMM
#[crio.runtime.runtimes.kata-fc]

# The crio.image table contains settings pertaining to the management of OCI images.
#
# CRI-O reads its configured registries defaults from the system wide
# containers-registries.conf(5) located in /etc/containers/registries.conf. If
# you want to modify just CRI-O, you can change the registries configuration in
# this file. Otherwise, leave insecure_registries and registries commented out to
# use the system's defaults from /etc/containers/registries.conf.
[crio.image]

# Default transport for pulling images from a remote container storage.
default_transport = "docker://"

# The path to a file containing credentials necessary for pulling images from
# secure registries. The file is similar to that of /var/lib/kubelet/config.json
global_auth_file = ""

# The image used to instantiate infra containers.
# This option supports live configuration reload.
pause_image = "k8s.gcr.io/pause:3.2"

# The path to a file containing credentials specific for pulling the pause_image from
# above. The file is similar to that of /var/lib/kubelet/config.json
# This option supports live configuration reload.
pause_image_auth_file = ""

# The command to run to have a container stay in the paused state.
# When explicitly set to "", it will fallback to the entrypoint and command
# specified in the pause image. When commented out, it will fallback to the
# default: "/pause". This option supports live configuration reload.
pause_command = "/pause"

# Path to the file which decides what sort of policy we use when deciding
# whether or not to trust an image that we've pulled. It is not recommended that
# this option be used, as the default behavior of using the system-wide default
# policy (i.e., /etc/containers/policy.json) is most often preferred. Please
# refer to containers-policy.json(5) for more details.
signature_policy = ""

# List of registries to skip TLS verification for pulling images. Please
# consider configuring the registries via /etc/containers/registries.conf before
# changing them here.
#insecure_registries = "[]"

# Controls how image volumes are handled. The valid values are mkdir, bind and
# ignore; the latter will ignore volumes entirely.
image_volumes = "mkdir"

# List of registries to be used when pulling an unqualified image (e.g.,
# "alpine:latest"). By default, registries is set to "docker.io" for
# compatibility reasons. Depending on your workload and usecase you may add more
# registries (e.g., "quay.io", "registry.fedoraproject.org",
# "registry.opensuse.org", etc.).
#registries = [
# 	"docker.io",
#]


# The crio.network table containers settings pertaining to the management of
# CNI plugins.
[crio.network]

# The default CNI network name to be selected. If not set or "", then
# CRI-O will pick-up the first one found in network_dir.
# cni_default_network = ""

# Path to the directory where CNI configuration files are located.
network_dir = "/etc/cni/net.d/"

# Paths to directories where CNI plugin binaries are located.
plugin_dirs = [
	"/opt/cni/bin/",
]

# A necessary configuration for Prometheus based metrics retrieval
[crio.metrics]

# Globally enable or disable metrics support.
enable_metrics = false

# The port on which the metrics server will listen.
metrics_port = 9090
```

</p>
</details>

</p>
</details>

---


</p>
</details>
<details>
<summary>Packages</summary>
<p>


# Packages

Have `dpkg`
<details>
<summary><tt>dpkg -l|egrep "(cc-oci-runtime|cc-runtime|runv|kata-runtime|kata-ksm-throttler|kata-containers-image|linux-container|qemu-)"</tt></summary>
<p>

```

```

</p>
</details>
No `rpm`

---


</p>
</details>

</p>
</details>

**Comment by GabyCT** [comment]
Runtime is `/usr/local/bin/kata-runtime`.

# `kata-env`

<details>
<summary><tt>/usr/local/bin/kata-runtime kata-env</tt></summary>
<p>

```toml
[Meta]
  Version = "1.0.25"

[Runtime]
  Debug = true
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  SandboxCgroupOnly = false
  Path = "/usr/local/bin/kata-runtime"
  [Runtime.Version]
    OCI = "1.0.1-dev"
    [Runtime.Version.Version]
      Semver = "2.0.0-rc0"
      Major = 2
      Minor = 0
      Patch = 0
      Commit = "d80e479ca201d3fdf75305b07e22ccc15ef6dda3"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "cloud-hypervisor v0.10.0-60-g6d30fe05"
  Path = "/usr/bin/cloud-hypervisor"
  BlockDeviceDriver = "virtio-blk"
  EntropySource = "/dev/urandom"
  SharedFS = "virtio-fs"
  VirtioFSDaemon = "/usr/libexec/kata-qemu/virtiofsd"
  Msize9p = 8192
  MemorySlots = 10
  PCIeRootPort = 0
  HotplugVFIOOnRootBus = false
  Debug = true

[Image]
  Path = "/usr/share/kata-containers/kata-containers.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinux-kata-v5.6-april-09-2020-84-virtiofs"
  Parameters = "systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket agent.log=debug agent.log=debug"

[Initrd]
  Path = ""

[Agent]
  Debug = true
  Trace = false
  TraceMode = ""
  TraceType = ""

[Host]
  Kernel = "5.4.0-1031-azure"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "18.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz"
    CPUs = 4
  [Host.Memory]
    Total = 16398304
    Free = 11972200
    Available = 15404980

[Netmon]
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = true
  Enable = false
  [Netmon.Version]
    Semver = "2.0.0-rc0"
    Major = 2
    Minor = 0
    Patch = 0
    Commit = "<<unknown>>"
```

</p>
</details>

**Comment by GabyCT** [comment]
There is also a problem that running the k8s test with CLH+virtiofs, pod information is left see http://jenkins.katacontainers.io/job/kata-containers-2.0-clh-crio-ubuntu-PR/3/console

**Comment by chavafg** [comment]
I think this was fixed with https://github.com/cri-o/cri-o/pull/4284

/cc @fidencio

**Comment by GabyCT** [comment]
@chavafg I tried with the latest CRI-O (the one that includes the changes) but it is still failing http://jenkins.katacontainers.io/job/kata-containers-2.0-clh-crio-ubuntu-PR/4/consoleFull

**Comment by fidencio** [comment]
@GabyCT, that sounds way to similar to the issue I fixed (the one pointed by @chavafg).
Looking at the logs it seems to still be using CRI-O 1.18.4, though.

Is there some easy way to ensure we're using latest release-1.18 branch here?

**Comment by fidencio** [comment]
> @GabyCT, that sounds way too similar to the issue I fixed (the one pointed by @chavafg).
> Looking at the logs it seems to still be using CRI-O 1.18.4, though.
> 
> Is there some easy way to ensure we're using latest release-1.18 branch here?

Oops, my bad, yes, may changes are part of 1.18.4 and for some reason I got confused Yesterday.
I'll try to reproduce this locally later Today, together with the issue brought up by @bergwolf.

**Comment by chavafg** [comment]
Taking a look at current CI Fedora+CRIO job, these tests are passing. 
http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-fedora-PR/407/console

Closing this issue.
